language: python
services:
  - docker
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - docker build -t squad42/imageupload .
  - sudo docker run -d -p5000:5000 squad42/imageupload
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m pytest
