apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
  creationTimestamp: "2020-01-13T16:35:21Z"
  generation: 106
  labels:
    app: image-upload
  name: image-upload
  namespace: default
  resourceVersion: "2317075"
  selfLink: /apis/apps/v1/namespaces/default/deployments/image-upload
  uid: b1351607-3622-11ea-8554-42010a84003c
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: image-upload
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: image-upload
    spec:
      containers:
      - env:
        - name: CATALOGUE_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: CATALOGUE_HOSTNAME
              name: image-upload-config
        - name: CATALOGUE_PORT
          valueFrom:
            configMapKeyRef:
              key: CATALOGUE_PORT
              name: image-upload-config
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              key: S3_BUCKET
              name: image-upload-config
        - name: S3_KEY
          valueFrom:
            configMapKeyRef:
              key: S3_KEY
              name: image-upload-config
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              key: S3_SECRET_ACCESS_KEY
              name: image-upload-config
        - name: DBX_ACCESS_TOKEN
          valueFrom:
            configMapKeyRef:
              key: DBX_ACCESS_TOKEN
              name: image-upload-config
        - name: CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              key: CONSUL_HOST
              name: image-upload-config
        - name: CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              key: CONSUL_PORT
              name: image-upload-config
        image: registry.hub.docker.com/slosquad42/image_upload:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/liveness
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: image-upload
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/readiness
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: "2020-01-13T16:35:21Z"
    lastUpdateTime: "2020-01-16T13:02:55Z"
    message: ReplicaSet "image-upload-6f7fc54884" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-01-20T01:56:39Z"
    lastUpdateTime: "2020-01-20T01:56:39Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 106
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
